export const recipes = [
  {
    id: 'entree_001',
    type: 'entrée',
    name: 'Salmorejo',
    portions: 4,
    ingredients: [
      { name: 'tomates', quantity: '4', detail: 'bien mûres' },
      { name: 'pain', quantity: '15-20cm', detail: 'de baguette' },
      { name: "huile d'olive", quantity: '2 cuillères à soupe' },
      { name: 'ail', quantity: '1 ou 2 gousses' },
      { name: 'œufs durs', quantity: '2' },
      { name: 'jambon cru', quantity: '2', detail: 'tranches' },
    ],
    cooking_time: 45,
    preparation_time: 15,
    instructions: [
      'Peler les tomates, puis les couper en gros morceaux.',
      'Oter la croûte du pain et mouiller légèrement la mie.',
      'Râper les œufs et couper le jambon cru en fines lamelles.',
      'Mixer les tomates avec la mie de pain, l’huile d’olive et l’ail.',
      'Servir dans des ramequins.',
    ],
  },
  {
    id: 'entree_002',
    type: 'entrée',
    name: 'Salade fromage frais, jambon cru et figues',
    portions: 4,
    ingredients: [
      { name: 'fromage frais', quantity: '200g' },
      { name: 'jambon cru', quantity: '100g' },
      { name: 'figues', quantity: '3-4', detail: 'bien mûres' },
      { name: "huile d'olive", quantity: '1 filet' },
    ],
    cooking_time: 45,
    preparation_time: 10,
    instructions: [
      'Découper les figues en 2 ou en 4 (ne pas forcément enlever la peau).',
      'Découper en petits cubes le fromage frais.',
      'Disposer les morceaux de figues au fond d’un plat et ajouter les morceaux de fromages frais par-dessus.',
      'Mettre un filet d’huile d’olive au-dessus du plat et rajouter des tranches de jambon cru pour tout recouvrir.',
    ],
  },
  {
    id: 'soupe_001',
    type: 'soupe',
    name: 'Soupe aux courgettes',
    portions: 4,
    ingredients: [
      { name: 'courgettes', quantity: '6' },
      { name: 'cube bouillon', quantity: '1' },
    ],
    preparation_time: 10,
    cooking_time: 45,
    instructions: [
      'Laver et découper les courgettes en gros morceaux.',
      'Les faire cuire dans une casserole avec un cube de bouillon pendant environ 45 minutes, puis mixer.',
    ],
  },
  {
    id: 'plat_001',
    type: 'plat',
    name: 'Quiche thon tomate',
    portions: 6,
    ingredients: [
      { name: 'tomates', quantity: '2-3', detail: 'mûres' },
      { name: 'thon', quantity: '180g', detail: 'en boîte' },
      { name: 'pâte feuilletée', quantity: '1' },
      { name: 'œufs', quantity: '3' },
      { name: 'crème fraîche', quantity: '20cl' },
      { name: 'lait', quantity: '10cl' },
      { name: 'moutarde à l’ancienne', quantity: '1 cuillère à soupe' },
      { name: 'gruyère', quantity: '50g', detail: 'râpé' },
    ],
    preparation_time: 20,
    cooking_time: 40,
    instructions: [
      'Découper les tomates en petits morceaux et enlever le jus.',
      'Émietter le thon.',
      'Dans un saladier, mélanger les tomates, le thon et la moutarde.',
      'Dans un autre saladier, mélanger les œufs, la crème fraîche, le lait et le gruyère.',
      'Ajouter la première préparation à la deuxième.',
      'Étaler la pâte feuilletée dans un plat, la piquer avec une fourchette et verser la préparation.',
      'Faire cuire 40 minutes au four à 180°C.',
    ],
  },
  {
    id: 'dessert_001',
    type: 'dessert',
    name: 'Crumble aux pommes',
    portions: 6,
    ingredients: [
      { name: 'pommes', quantity: '5-6', detail: 'épluchées et coupées' },
      { name: 'beurre', quantity: '100g', detail: 'froid' },
      { name: 'farine', quantity: '150g' },
      { name: 'sucre', quantity: '125g' },
    ],
    preparation_time: 15,
    cooking_time: 30,
    instructions: [
      'Peler et découper les pommes en morceaux, les mettre dans un plat.',
      'Mélanger dans un récipient le beurre coupé en morceaux, le sucre et la farine jusqu’à obtenir une texture sableuse.',
      'Recouvrir les pommes du mélange et enfourner à 180°C pendant 30 minutes.',
    ],
    variants: [
      'Ajouter quelques carrés de chocolat avec les pommes pour plus de gourmandise.',
    ],
  },
];
